account_id = ""
name = "graphql-subscriptions"
route = ""
type = "webpack"
webpack_config = "webpack.config.js"
workers_dev = true
zone_id = ""

[build]
watch_dir = "src"
[build.upload]
format = "service-worker"
